CREATE TABLE IF NOT EXISTS tbl_calculation (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  TIMESTAMP  datetime DEFAULT NULL,
  CALCULATION_DATA longtext NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS tbl_secret_codes (
  CALCULATION_ID int(11) NOT NULL,
  CODE BIGINT NOT NULL
);